version: "3.10"

services:
  database:
    image: postgres:15
    container_name: database
    volumes:
      - ~/.pg/pg_data/page-analyzer:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  page_analyzer:
    build:
      dockerfile: Dockerfile
      context: .
    image: page-analyzer:latest
    container_name: page-analyzer
    depends_on:
      - database
#    ports:
#      - '5000:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: poetry run gunicorn -w 5 -b 0.0.0.0:8000 page_analyzer:app
